tracer.property: "I AM THE DEFAULT"

spring.jpa.database: "MYSQL"
spring.datasource.platform:  "mysql"
spring.jpa.show-sql: "false"
spring.database.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://ec2-3-6-82-226.ap-south-1.compute.amazonaws.com:3306/rapidminer_server"
spring.datasource.username: "authuser"
spring.datasource.password: "authuser"
#spring.datasource.testWhileIdle: "true"
#spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL5Dialect"
redis.server: "redis"
redis.port: "6379"
#signing.key: "345345fsdfsf5345"
security.oauth2.resource.userInfoUri: "http://localhost:8901/auth/user"